### ISSUE TITLE
Discord Bug

### ISSUE THREAD

**Issue by louanbastos** [aXenDeveloper/ips-app-advanced-serverlist#3]
```php
UPDATE `axenserverlist_servers` axenserverlist_servers  SET `axenserverlist_status`=1,`axenserverlist_current_players`=NULL,`axenserverlist_max_players`=NULL,`axenserverlist_name_default_text`=NULL,`axenserverlist_game_long`='Discord',`axenserverlist_connect_link`=NULL,`axenserverlist_protocol`='discord' WHERE axenserverlist_id=2 
IPS\Db\Exception: Column 'axenserverlist_current_players' cannot be null (1048)
#0 /home/xxxxxx/public_html/system/Db/Db.php(1161): IPS\_Db->preparedQuery('/*xxxxxx_ipb::g...', Array)
#1 /home/xxxxxx/public_html/applications/axenserverlist/sources/Servers/Servers.php(268): IPS\_Db->update('`axenserv...', '`axenserverlist...', 'WHERE axenserve...')
#2 /home/xxxxxx/public_html/system/Node/Model.php(3315): IPS\axenserverlist\_Servers->postSaveForm(Array)
#3 /home/xxxxxx/public_html/init.php(893) : eval()'d code(184): IPS\Node\_Model->saveForm(Array)
#4 /home/xxxxxx/public_html/system/Node/Controller.php(413): IPS\Node\radtags_hook_C_NodeModel->saveForm(Array)
#5 /home/xxxxxx/public_html/system/Dispatcher/Controller.php(90): IPS\Node\_Controller->form()
#6 /home/xxxxxx/public_html/system/Node/Controller.php(62): IPS\Dispatcher\_Controller->execute()
#7 /home/xxxxxx/public_html/applications/axenserverlist/modules/admin/servers/servers.php(36): IPS\Node\_Controller->execute()
#8 /home/xxxxxx/public_html/system/Dispatcher/Dispatcher.php(152): IPS\axenserverlist\modules\admin\servers\_servers->execute()
#9 /home/xxxxxx/public_html/admin/index.php(14): IPS\_Dispatcher->run()
#10 {main}
```

How can i fix it? This is happen when i try to create/update a discord server.

**Comment by aXenDeveloper** [comment]
Hi,
Thanks for the reporting. I will fix in the next update.

The app cannot find "**instant_invite**" value. Please follow to documentation https://github.com/aXenDeveloper/ips-app-advanced-serverlist#configuration-
