### ISSUE TITLE
❔ Error

### ISSUE THREAD

**Issue by heckair** [aXenDeveloper/ips-app-advanced-serverlist#55]
Hi ✌
I wanted to install Advenced Server List, but I got an error
```
Error: Call to undefined method IPS\Image::supportedExtensions() (0)
#0 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/system/Node/Controller.php(489): IPS\axenserverlist\_Mods->form()
#1 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/system/Node/Controller.php(388): IPS\Node\_Controller->_addEditForm()
#2 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/system/Dispatcher/Controller.php(90): IPS\Node\_Controller->form()
#3 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/system/Node/Controller.php(62): IPS\Dispatcher\_Controller->execute()
#4 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/applications/axenserverlist/modules/admin/servers/mods.php(35): IPS\Node\_Controller->execute()
#5 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/system/Dispatcher/Dispatcher.php(152): IPS\axenserverlist\modules\admin\servers\_mods->execute()
#6 /var/www/vhosts/sweatylife.ga/forum.sweatylife.ga/admin/index.php(14): IPS\_Dispatcher->run()
#7 {main}
```

**Comment by aXenDeveloper** [comment]
IPS 4.6?

**Comment by heckair** [comment]
> IPS 4.6?

No, 4.5.4.2

**Comment by aXenDeveloper** [comment]
https://github.com/aXenDeveloper/ips-app-advanced-serverlist/issues/45
