### ISSUE TITLE
IPS\Http\Request\CurlException:  <url> malformed

### ISSUE THREAD

**Issue by Doker96** [aXenDeveloper/ips-app-advanced-serverlist#57]
```
IPS\Http\Request\CurlException: 
<url> malformed (3)
#0 /sites/site.ru/system/Http/Request/Curl.php(422): IPS\Http\Request\_Curl->_execute()
#1 /sites/site.ru/system/Http/Request/Curl.php(298): IPS\Http\Request\_Curl->_executeAndFollowRedirects('GET', NULL)
#2 /sites/site.ru/applications/axenserverlist/sources/Servers/Update.php(24): IPS\Http\Request\_Curl->get()
#3 /sites/site.ru/applications/axenserverlist/tasks/aXenServersQueryServers.php(53): IPS\axenserverlist\Servers\_Update->server(Array, true)
#4 /sites/site.ru/system/Task/Task.php(266): IPS\axenserverlist\tasks\_aXenServersQueryServers->execute()
#5 /sites/site.ru/applications/core/modules/admin/settings/advanced.php(754): IPS\_Task->run()
#6 /sites/site.ru/system/Dispatcher/Controller.php(90): IPS\core\modules\admin\settings\_advanced->runTask()
#7 /sites/site.ru/applications/core/modules/admin/settings/advanced.php(38): IPS\Dispatcher\_Controller->execute()
#8 /sites/site.ru/system/Dispatcher/Dispatcher.php(153): IPS\core\modules\admin\settings\_advanced->execute()
#9 /sites/site.ru/admin/index.php(13): IPS\_Dispatcher->run()
#10 {main}
```

I try to run task, but get this error

**Comment by Doker96** [comment]
4.6.12.1
This error is related to the Discord server. If you remove the discord server from the list of servers, the error disappears. When adding a Discord server to the list of servers, the same error occurs.

**Comment by Doker96** [comment]
Removed Discord server and mod from server list. After - added the mod and the server again. The problem is gone. Thank you)
