### ISSUE TITLE
KF2 server list query

### ISSUE THREAD

**Issue by bouncemonk3y** [aXenDeveloper/ips-app-advanced-serverlist#67]
Hi, The killing floor 2 server query is not working.

Unable to locate Protocols class for 'killing floor 2'!

#0 /var/www/vhosts/**********/httpdocs/applications/axenserverlist/sources/GameQ/GameQ.php(199): GameQ\Server->__construct()
#1 /var/www/vhosts/**********/httpdocs/applications/axenserverlist/sources/Servers/Update/Queries.php(72): GameQ\GameQ->addServer()
#2 /var/www/vhosts/**********/httpdocs/applications/axenserverlist/sources/Servers/Update/Update.php(21): IPS\axenserverlist\Servers\Update\_Queries->getDataFromGameQ()
#3 /var/www/vhosts/**********/httpdocs/applications/axenserverlist/modules/admin/servers/servers.php(99): IPS\axenserverlist\Servers\_Update->server()
#4 /var/www/vhosts/**********/httpdocs/system/Dispatcher/Controller.php(107): IPS\axenserverlist\modules\admin\servers\_servers->debug()
#5 /var/www/vhosts/**********/httpdocs/system/Node/Controller.php(69): IPS\Dispatcher\_Controller->execute()
#6 /var/www/vhosts/**********/httpdocs/applications/axenserverlist/modules/admin/servers/servers.php(113): IPS\Node\_Controller->execute()
#7 /var/www/vhosts/**********/httpdocs/system/Dispatcher/Dispatcher.php(153): IPS\axenserverlist\modules\admin\servers\_servers->execute()
#8 /var/www/vhosts/**********/httpdocs/admin/index.php(13): IPS\_Dispatcher->run()
#9 {main}

**Comment by aXenDeveloper** [comment]
Hi,
Which data you are provide?
